//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancer_x_Subcategoria
    {
        public long ID { get; set; }
        public long ID_CANCER { get; set; }
        public long ID_SUBCATEGORIA { get; set; }
    }
}
