//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GENPsCEntities1 : DbContext
    {
        public GENPsCEntities1()
            : base("name=GENPsCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cancer> Cancer { get; set; }
        public virtual DbSet<Cancer_x_SNP> Cancer_x_SNP { get; set; }
        public virtual DbSet<Cancer_x_Subcategoria> Cancer_x_Subcategoria { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Dado> Dado { get; set; }
        public virtual DbSet<REL_Cancer_x_Subcategoria_x_SNP> REL_Cancer_x_Subcategoria_x_SNP { get; set; }
        public virtual DbSet<REL_SNP_x_Subcategoria> REL_SNP_x_Subcategoria { get; set; }
        public virtual DbSet<SNPs> SNPs { get; set; }
        public virtual DbSet<Subcategoria> Subcategoria { get; set; }
        public virtual DbSet<vw_Categoria_x_SubCategoria> vw_Categoria_x_SubCategoria { get; set; }
        public virtual DbSet<vw_SNPs_x_Cancer> vw_SNPs_x_Cancer { get; set; }
    }
}
