//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNPs
    {
        public long ID { get; set; }
        public string Nome { get; set; }
        public string Localizacao { get; set; }
        public string Cor { get; set; }
        public int Ordem { get; set; }
        public string Mecanismo { get; set; }
        public string TargetGene { get; set; }
        public long ID_CANCER { get; set; }
    }
}
