//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Categoria_x_SubCategoria
    {
        public string NomeCategoria { get; set; }
        public string CorCategoria { get; set; }
        public long ID_SUBCATEGORIA { get; set; }
        public string NomeSubCategoria { get; set; }
        public long ID_CATEGORIA { get; set; }
    }
}
