//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SNPs_x_Cancer
    {
        public long ID_SNPs { get; set; }
        public string NomeSNPs { get; set; }
        public string LocalizacaoSNPs { get; set; }
        public string CorSNPs { get; set; }
        public int OrdemSNPs { get; set; }
        public string MecanismoSNPs { get; set; }
        public string TargetGeneSNPs { get; set; }
        public long ID_CANCER { get; set; }
        public string NomeCancer { get; set; }
    }
}
